#!/bin/sh

set -eu

log() {
  local message priority
  priority=$1
  message=$2
  logger -p "$priority" -t puavo-autoreboot "$message" || true
}

if [ "$(puavo-conf puavo.admin.autoreboot.enabled)" = 'false' ]; then
  exit 0
fi

log notice 'automatic reboot enabled'

# if puavo-ers user is active we need to handle reboot through it
if ! puavo_ers_uid="$(id -u puavo-ers)"; then
  log err 'could not determine puavo-ers user id'
  exit 1
fi

puavo_ers_run_dir="/run/user/${puavo_ers_uid}"
if [ -e "$puavo_ers_run_dir" ]; then
  log err 'puavo-ers user is active, requesting puavo-ers-applet to reboot'
  touch "${puavo_ers_run_dir}/.reboot"
  exit 0
fi

log notice 'triggering reboot'

exec /usr/sbin/reboot
